# Generated by Django 5.0.3 on 2024-03-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="image",
        ),
        migrations.AddField(
            model_name="patient",
            name="hair",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="patient",
            name="profile_photo",
            field=models.ImageField(
                default="img/default.jpg", upload_to="patient_images"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(max_length=20),
        ),
    ]
