# Generated by Django 5.0.3 on 2024-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_remove_patient_image_patient_hair_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="appointment",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="treatment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
