# Generated by Django 5.0.3 on 2024-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_alter_patient_appointment_alter_patient_treatment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=models.TextField(blank=True, null=True),
        ),
    ]
