# Generated by Django 5.0.3 on 2024-03-19 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_patient_medical_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="hair",
        ),
    ]
